blog/urls.py
from django.urls import path
from .views import BlogView, BlogDetailsView

app_name = 'blog'

urlpatterns = [
    path('', BlogView.as_view(), name="blogs"),
    path('category/<str:category>', BlogView.as_view(), name="category"),
    path('details/<int:pk>',BlogDetailsView.as_view(), name="blog-details"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('root.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path("captcha/", include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Agent(models.Model):
    name = models.CharField(max_length=120)
    rank = models.CharField(max_length=120)
    explane = models.CharField(max_length=200)
    x = models.TextField()
    facebook = models.TextField()
    insta =models.TextField()
    linkein =models.TextField()
    status = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name


class Category(models.Model):
    title = models.CharField(max_length=120)
    status = models.BooleanField(default=True)
    
    def __str__(self):
        return self.title
    
class Tag(models.Model):
    title = models.CharField(max_length=30)
    status = models.BooleanField(default=True)
    
    def __str__(self):
        return self.title

class SpecialService(models.Model):
    title = models.CharField(max_length=120)
    status = models.BooleanField(default=True)
    
    def __str__(self):
        return self.title

class Blog(models.Model):
    title = models.CharField(max_length=120)
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)
    desc1 = models.TextField()
    desc2 = models.TextField()
    desc3 = models.TextField()
    special_service = models.ForeignKey(SpecialService, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)
    tag = models.ManyToManyField(Tag)
    img1 = models.ImageField(upload_to="blog", default="default.jpg")
    img2 = models.ImageField(upload_to="blog", default="default.jpg")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    
    def truncate_chars(self):
        return self.desc1[:200] 
    
class Comments(models.Model):
    service = models.ForeignKey(Blog, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    message = models.TextField()
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.service.title
    

blog/forms.py
from django import forms
from .models import Comments

class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ["name", "message"]

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Blog, Comments
from django.core.paginator import Paginator
from django.contrib import messages
from .forms import CommentsForm

# Create your views here.

class BlogView(ListView):
    model = Blog
    template_name = 'blog/blog.html'
    context_object_name = "blogs"
    paginate_by = 2

    def get_queryset(self):
        if self.kwargs.get("category"):
            blog = self.model.objects.filter(category__title=self.kwargs.get("category"), status=True)
        elif self.kwargs.get("search"):
            search = self.request.GET.get("search")
            blog = self.model.objects.filter(title__contains=search, status=True)
        else:
            blog = Blog.objects.filter(status=True)
        return blog
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        first = 1
        blog_paginate = Paginator(self.get_queryset(), 2)
        last = blog_paginate.num_pages
        context["first"] = first
        context["last"] = last
        
        return context
    

class BlogDetailsView(DetailView):
    model = Blog
    template_name = 'blog/single-post.html'

    def get_context_data(self, **kwargs):
        id = self.kwargs["pk"]
        blog = get_object_or_404(Blog, id=id)
        context = super().get_context_data(**kwargs)
        context["comments"] = Comments.objects.filter(status=True, service=blog.id)
        return context
    
    def post(self, request, *args, **kwargs):
        form = CommentsForm(request.POST)
        if request.user.is_authenticated:
            if form.is_valid():
                id = self.kwargs["pk"]
                blog = get_object_or_404(Blog, id=id)
                comment = form.save(commit=False)
                comment.blog = blog
                comment.save()
                messages.add_message(self.request, messages.SUCCESS, "successfully sent")
                return redirect(self.request.path_info)
            else:
                messages.add_message(request, messages.ERROR, "invalid data")
                return redirect(self.request.path_info)
        else:
            return redirect("accounts:login")

templates/blog/blog.html
{% extends "base.html" %}
{% load static %}
{% block "content" %}

  <main class="main">

    <!-- Page Title -->
    <div class="page-title position-relative">
      <div class="container d-lg-flex justify-content-between align-items-center">
        <h1 class="mb-2 mb-lg-0">Blog</h1>
        <nav class="breadcrumbs">
          <ol>
            <li><a href="index.html">Home</a></li>
            <li class="current">Blogs</li>
          </ol>
        </nav>
      </div>
    </div><!-- End Page Title -->

    <div class="container">
      <div class="row">

        <div class="col-lg-8">

          <!-- Blog Posts Section -->
          <section id="blog-posts" class="blog-posts section">

            <div class="container">
              <div class="row gy-4">
                {% for blog in blogs %}
                <div class="col-lg-6">
                  <article class="position-relative h-100">

                    <div class="post-img position-relative overflow-hidden">
                      <img src={% static "assets/img/blog/blog-1.jpg" %} class="img-fluid" alt="">
                      <span class="post-date">{{blog.created_at}}</span>
                    </div>

                    <div class="post-content d-flex flex-column">

                      <h3 class="post-title">{{blog.title}}</h3>

                      <div class="meta d-flex align-items-center">
                        <div class="d-flex align-items-center">
                          <i class="bi bi-person"></i> <span class="ps-2">John Doe</span>
                        </div>
                        <span class="px-3 text-black-50">/</span>
                        <div class="d-flex align-items-center">
                          <i class="bi bi-folder2"></i> <span class="ps-2">Politics</span>
                        </div>
                      </div>

                      <p>
                        {{blog.truncate_chars}}
                      </p>

                      <hr>

                      <a href={% url "blog:blog-details" pk=blog.id%} class="readmore stretched-link"><span>Read More</span><i class="bi bi-arrow-right"></i></a>

                    </div>

                  </article>
                </div><!-- End post list item -->
                {% endfor %}

              </div>
            </div>

          </section><!-- /Blog Posts Section -->

          <!-- Blog Pagination Section -->
          <section id="blog-pagination" class="blog-pagination section">

            <div class="container">
              <div class="d-flex justify-content-center">
                <ul>
                  <li><a href="#"><i class="bi bi-chevron-left"></i></a></li>
                  <li><a href="#">1</a></li>
                  <li><a href="#" class="active">2</a></li>
                  <li><a href="#">3</a></li>
                  <li><a href="#">4</a></li>
                  <li>...</li>
                  <li><a href="#">10</a></li>
                  <li><a href="#"><i class="bi bi-chevron-right"></i></a></li>
                </ul>
              </div>
            </div>

          </section><!-- /Blog Pagination Section -->

        </div>

        <div class="col-lg-4 sidebar">

          <div class="widgets-container">

            <!-- Blog Author Widget 2 -->
            <div class="blog-author-widget-2 widget-item">

              <div class="d-flex flex-column align-items-center">
                <img src={% static "assets/img/blog/blog-author.jpg" %} class="rounded-circle flex-shrink-0" alt="">
                <h4>Jane Smith</h4>
                <div class="social-links">
                  <a href="https://x.com/#"><i class="bi bi-twitter-x"></i></a>
                  <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                  <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
                  <a href="https://instagram.com/#"><i class="biu bi-linkedin"></i></a>
                </div>

                <p>
                  Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas repellat voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
                </p>

              </div>
            </div><!--/Blog Author Widget 2 -->

            <!-- Search Widget -->
            <div class="search-widget widget-item">

              <h3 class="widget-title">Search</h3>
              <form action="">
                <input type="text">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
              </form>

            </div><!--/Search Widget -->

            <!-- Recent Posts Widget -->
            <div class="recent-posts-widget widget-item">

              <h3 class="widget-title">Recent Posts</h3>

              <div class="post-item">
                <img src={% static "assets/img/blog/blog-recent-1.jpg" %} alt="" class="flex-shrink-0">
                <div>
                  <h4><a href="blog-details.html">Nihil blanditiis at in nihil autem</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>
              </div><!-- End recent post item-->

            </div><!--/Recent Posts Widget -->

            <!-- Tags Widget -->
            <div class="tags-widget widget-item">

              <h3 class="widget-title">Tags</h3>
              <ul>
                <li><a href="#">App</a></li>
                <li><a href="#">IT</a></li>
                <li><a href="#">Business</a></li>
                <li><a href="#">Mac</a></li>
                <li><a href="#">Design</a></li>
                <li><a href="#">Office</a></li>
                <li><a href="#">Creative</a></li>
                <li><a href="#">Studio</a></li>
                <li><a href="#">Smart</a></li>
                <li><a href="#">Tips</a></li>
                <li><a href="#">Marketing</a></li>
              </ul>

            </div><!--/Tags Widget -->

          </div>

        </div>

      </div>
    </div>

  </main>
  {% endblock "content" %}